import json
import os

en_file = "lib/l10n/app_en.arb"
ar_file = "lib/l10n/app_ar.arb"

new_en = {
  "about": "About",
  "servicesAndPricing": "Services & Pricing",
  "allPricesInEgp": "All prices in Egyptian Pounds (EGP)",
  "customerReviews": "Customer Reviews",
  "seeAll": "See all",
  "standardBooking": "Standard Booking",
  "vipHomeService": "VIP Home Service",
  "bookingConfirmed": "✅ Booking confirmed successfully!",
  "bookingNewService": "Booking a new service",
  "serviceTypeLabel": "Service Type",
  "tailoringLabel": "Tailoring",
  "repairLabel": "Repair",
  "clothingType": "Clothing Type",
  "selectGarmentHint": "Select garment type...",
  "preferredDate": "Preferred Date",
  "tapToSelectDate": "Tap to select a date...",
  "timeSlot": "Time Slot",
  "specialNotes": "Special Notes",
  "specialNotesHint": "Any special instructions for the tailor...",
  "orderSummary": "Order Summary",
  "tailor": "Tailor",
  "service": "Service",
  "garment": "Garment",
  "date": "Date",
  "time": "Time",
  "notSelected": "Not selected",
  "estimatedTotal": "Estimated Total",
  "confirmBooking": "Confirm Booking",
  "vipBookingConfirmed": "🌟 VIP Booking confirmed! The tailor will visit you.",
  "vipHomeVisitRequest": "VIP Home Visit Request",
  "premiumVipService": "Premium VIP Service",
  "vipSurchargeNotice": "A professional tailor will visit your home. An additional VIP surcharge of 200 EGP applies.",
  "visitAddress": "Visit Address",
  "enterAddressHint": "Enter your full home address...",
  "useCurrentLocation": "Use Current Location",
  "enterAddressManually": "Enter Address Manually",
  "appointmentDate": "Appointment Date",
  "tapToSelectAppointmentDate": "Tap to select appointment date...",
  "preferredTime": "Preferred Time",
  "measurementNotes": "Measurement Notes",
  "measurementNotesHint": "Fabric type, body measurements, urgency level...",
  "vipOrderSummary": "VIP Order Summary",
  "address": "Address",
  "notProvided": "Not provided",
  "baseServiceFee": "Base Service Fee",
  "vipSurcharge": "VIP Surcharge ✨",
  "total": "Total",
  "confirmVipBooking": "Confirm VIP Booking",
  "welcomeBack": "Welcome back!",
  "createAccount": "Create your account",
  "login": "Login",
  "signUp": "Sign Up",
  "iAmA": "I am a:",
  "customer": "Customer",
  "tailorRole": "Tailor",
  "fullName": "Full Name",
  "enterFullName": "Enter your full name",
  "email": "Email",
  "enterEmail": "you@example.com",
  "password": "Password",
  "enterPassword": "Enter your password",
  "dontHaveAccount": "Don't have an account? ",
  "alreadyHaveAccount": "Already have an account? ",
  "yourTailorOneTapAway": "Your Tailor, One Tap Away",
  "tailorHub": "TailorHub",
  "myProfile": "My Profile",
  "myAccount": "My Account",
  "paymentMethods": "Payment Methods",
  "helpAndSupport": "Help & Support",
  "logOut": "Log Out",
  "logOutConfirmationTitle": "Log Out",
  "logOutConfirmationContent": "Are you sure you want to log out of your account?",
  "cancel": "Cancel",
  "notifications": "Notifications",
  "noNotificationsYet": "No notifications yet",
  "noNotificationsDesc": "You will see order updates and messages here.",
  "justNow": "Just now",
  "hoursAgo": "2 hours ago",
  "dayAgo": "1 day ago",
  "daysAgo": "3 days ago",
  "orderReadyTitle": "Order Ready for Pickup!",
  "orderReadyMessage": "Your Formal Suit is ready. Please visit Ahmed El-Fashionista to collect it.",
  "newMessageTitle": "New Message",
  "newMessageMessage": "Fatma's Couture sent you a message regarding your Shirt Repair.",
  "orderInProgressTitle": "Order In Progress",
  "orderInProgressMessage": "Omar The Tailor has started working on your Custom Galabiya.",
  "vipBookingConfirmedTitle": "VIP Booking Confirmed",
  "vipBookingConfirmedMessage": "Ahmed El-Fashionista accepted your VIP Home Service request for tomorrow.",
  "myOrders": "My Orders",
  "statusPending": "Pending",
  "statusInProgress": "In Progress",
  "statusCompleted": "Completed"
}

new_ar = {
  "about": "نبذة",
  "servicesAndPricing": "الخدمات والأسعار",
  "allPricesInEgp": "جميع الأسعار بالجنيه المصري (EGP)",
  "customerReviews": "تقييمات العملاء",
  "seeAll": "عرض الكل",
  "standardBooking": "حجز عادي",
  "vipHomeService": "خدمة VIP منزلية",
  "bookingConfirmed": "✅ تم تأكيد الحجز بنجاح!",
  "bookingNewService": "حجز خدمة جديدة",
  "serviceTypeLabel": "نوع الخدمة",
  "tailoringLabel": "تفصيل",
  "repairLabel": "تصليح",
  "clothingType": "نوع الملابس",
  "selectGarmentHint": "اختر نوع الملابس...",
  "preferredDate": "التاريخ المفضل",
  "tapToSelectDate": "اضغط لاختيار التاريخ...",
  "timeSlot": "الوقت المفضل",
  "specialNotes": "ملاحظات خاصة",
  "specialNotesHint": "أي تعليمات خاصة للخياط...",
  "orderSummary": "ملخص الطلب",
  "tailor": "الخياط",
  "service": "الخدمة",
  "garment": "الملابس",
  "date": "التاريخ",
  "time": "الوقت",
  "notSelected": "غير محدد",
  "estimatedTotal": "الإجمالي التقديري",
  "confirmBooking": "تأكيد الحجز",
  "vipBookingConfirmed": "🌟 تم تأكيد حجز VIP! سيزورك الخياط.",
  "vipHomeVisitRequest": "طلب زيارة منزلية VIP",
  "premiumVipService": "خدمة VIP المتميزة",
  "vipSurchargeNotice": "سيزورك خياط محترف في منزلك. تطبق رسوم VIP إضافية بقيمة 200 جنيه.",
  "visitAddress": "عنوان الزيارة",
  "enterAddressHint": "أدخل عنوان منزلك بالكامل...",
  "useCurrentLocation": "استخدام الموقع الحالي",
  "enterAddressManually": "إدخال العنوان يدوياً",
  "appointmentDate": "تاريخ الموعد",
  "tapToSelectAppointmentDate": "اضغط لاختيار تاريخ الموعد...",
  "preferredTime": "الوقت المفضل",
  "measurementNotes": "ملاحظات المقاسات",
  "measurementNotesHint": "نوع القماش، مقاسات الجسم، درجة الاستعجال...",
  "vipOrderSummary": "ملخص طلب VIP",
  "address": "العنوان",
  "notProvided": "لم يتم التوفير",
  "baseServiceFee": "رسوم الخدمة الأساسية",
  "vipSurcharge": "رسوم VIP الإضافية ✨",
  "total": "الإجمالي",
  "confirmVipBooking": "تأكيد حجز VIP",
  "welcomeBack": "مرحباً بعودتك!",
  "createAccount": "إنشاء حسابك",
  "login": "تسجيل الدخول",
  "signUp": "إنشاء حساب",
  "iAmA": "أنا:",
  "customer": "عميل",
  "tailorRole": "خياط",
  "fullName": "الاسم الكامل",
  "enterFullName": "أدخل اسمك الكامل",
  "email": "البريد الإلكتروني",
  "enterEmail": "you@example.com",
  "password": "كلمة المرور",
  "enterPassword": "أدخل كلمة المرور",
  "dontHaveAccount": "ليس لديك حساب؟ ",
  "alreadyHaveAccount": "لديك حساب بالفعل؟ ",
  "yourTailorOneTapAway": "خياطك بلمسة واحدة",
  "tailorHub": "تيلور هاب",
  "myProfile": "حسابي الشخصي",
  "myAccount": "حسابي",
  "paymentMethods": "طرق الدفع",
  "helpAndSupport": "المساعدة والدعم",
  "logOut": "تسجيل الخروج",
  "logOutConfirmationTitle": "تسجيل الخروج",
  "logOutConfirmationContent": "هل أنت متأكد أنك تريد تسجيل الخروج من حسابك؟",
  "cancel": "إلغاء",
  "notifications": "الإشعارات",
  "noNotificationsYet": "لا توجد إشعارات بعد",
  "noNotificationsDesc": "سترى تحديثات الطلبات والرسائل هنا.",
  "justNow": "الآن",
  "hoursAgo": "منذ ساعتين",
  "dayAgo": "منذ يوم واحد",
  "daysAgo": "منذ 3 أيام",
  "orderReadyTitle": "الطلب جاهز للاستلام!",
  "orderReadyMessage": "البدلة الرسمية الخاصة بك جاهزة. يرجى زيارة أحمد فاشونيستا لاستلامها.",
  "newMessageTitle": "رسالة جديدة",
  "newMessageMessage": "أرسلت لك خياطة فاطمة رسالة بخصوص تصليح القميص.",
  "orderInProgressTitle": "الطلب قيد التنفيذ",
  "orderInProgressMessage": "بدأ عمر الخياط العمل على جلابيتك المخصصة.",
  "vipBookingConfirmedTitle": "تم تأكيد حجز VIP",
  "vipBookingConfirmedMessage": "وافق أحمد فاشونيستا على طلب الزيارة المنزلية VIP غدًا.",
  "myOrders": "طلباتي",
  "statusPending": "قيد الانتظار",
  "statusInProgress": "قيد التنفيذ",
  "statusCompleted": "مكتمل"
}

def update_json(filepath, new_data):
    if os.path.exists(filepath):
        with open(filepath, 'r', encoding='utf-8') as f:
            data = json.load(f)
    else:
        data = {}
    
    data.update(new_data)
    
    with open(filepath, 'w', encoding='utf-8') as f:
        json.dump(data, f, ensure_ascii=False, indent=2)
        f.write("\n")

update_json(en_file, new_en)
update_json(ar_file, new_ar)
print("ARB files updated successfully!")
