// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB5ALtWUeFTyEmgIRIYzpq05dXlCZm50iI',
    appId: '1:749492531358:web:dd486af643fdfcf5424b8f',
    messagingSenderId: '749492531358',
    projectId: 'tailorhub-3acc1',
    authDomain: 'tailorhub-3acc1.firebaseapp.com',
    storageBucket: 'tailorhub-3acc1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAbYhdtMIP6nwPLaB7RGRtrczd-zoQEjOk',
    appId: '1:749492531358:android:ed9a27a292a5ee54424b8f',
    messagingSenderId: '749492531358',
    projectId: 'tailorhub-3acc1',
    storageBucket: 'tailorhub-3acc1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAW65Ew6MwCw4OnYhoBRdlvjp17rRIv00s',
    appId: '1:749492531358:ios:06552b4875d310d7424b8f',
    messagingSenderId: '749492531358',
    projectId: 'tailorhub-3acc1',
    storageBucket: 'tailorhub-3acc1.firebasestorage.app',
    iosBundleId: 'com.example.tailorShop',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAW65Ew6MwCw4OnYhoBRdlvjp17rRIv00s',
    appId: '1:749492531358:ios:06552b4875d310d7424b8f',
    messagingSenderId: '749492531358',
    projectId: 'tailorhub-3acc1',
    storageBucket: 'tailorhub-3acc1.firebasestorage.app',
    iosBundleId: 'com.example.tailorShop',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB5ALtWUeFTyEmgIRIYzpq05dXlCZm50iI',
    appId: '1:749492531358:web:cd74f165ce6a9867424b8f',
    messagingSenderId: '749492531358',
    projectId: 'tailorhub-3acc1',
    authDomain: 'tailorhub-3acc1.firebaseapp.com',
    storageBucket: 'tailorhub-3acc1.firebasestorage.app',
  );
}
